// Hermes/JSI replacement for v8_runner.cpp.
// Identical external behaviour: same runner lifecycle, same driver scripts,
// same event-loop pump.  Only the JS engine changes (V8 → Hermes via JSI).

#include "hermes_runner.h"

// BG_FULL_BUNDLE_JS — generated by CMake from src/bg_full_bundle.min.js
#include "bg_full_bundle.h"
#include "bgutils_bundle.h"
#include "constants.h"
#include "http_client.h"

#include <hermes/hermes.h>
#include <jsi/jsi.h>

#include <algorithm>
#include <chrono>
#include <cstdio>
#include <cstring>
#include <functional>
#include <random>
#include <string>
#include <thread>
#include <variant>
#include <vector>

namespace jsi = facebook::jsi;

namespace epotoken::hermes_runner {

// ---------------------------------------------------------------------------
// Timer entry
// ---------------------------------------------------------------------------

struct timer_entry {
    int64_t id;
    std::chrono::steady_clock::time_point fire_at;
    bool    repeat;
    int64_t interval_ms;
    jsi::Value callback;   // holds a reference counted by the Hermes GC

    timer_entry(int64_t id_,
                std::chrono::steady_clock::time_point t,
                bool rep, int64_t iv,
                jsi::Value&& cb)
        : id(id_), fire_at(t), repeat(rep), interval_ms(iv),
          callback(std::move(cb)) {}

    // Move-only: jsi::Value is not copyable.
    timer_entry(timer_entry&&) = default;
    timer_entry& operator=(timer_entry&&) = default;
    timer_entry(const timer_entry&) = delete;
    timer_entry& operator=(const timer_entry&) = delete;
};

// ---------------------------------------------------------------------------
// Runner struct
// ---------------------------------------------------------------------------

struct runner {
    std::unique_ptr<facebook::hermes::HermesRuntime> rt;
    std::vector<timer_entry> timers;
    int64_t next_timer_id = 1;
};

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

static jsi::Value eval_js(runner* r, const std::string& src,
                           const char* name = "<epo>") {
    return r->rt->evaluateJavaScript(
        std::make_shared<jsi::StringBuffer>(src), name);
}

static jsi::Value get_nested(runner* r, const std::string& path) {
    jsi::Runtime& rt = *r->rt;
    jsi::Value val(rt, rt.global());
    size_t start = 0;
    while (start < path.size()) {
        auto dot = path.find('.', start);
        std::string key = (dot == std::string::npos)
            ? path.substr(start) : path.substr(start, dot - start);
        if (!val.isObject()) return jsi::Value::undefined();
        val = val.getObject(rt).getProperty(rt, key.c_str());
        start = (dot == std::string::npos) ? path.size() : dot + 1;
    }
    return val;
}

static bool js_bool(runner* r, const char* path) {
    auto v = get_nested(r, path);
    return v.isBool() && v.getBool();
}

static std::string js_string(runner* r, const char* path) {
    auto v = get_nested(r, path);
    return v.isString() ? v.getString(*r->rt).utf8(*r->rt) : std::string{};
}

// ---------------------------------------------------------------------------
// Timer host functions
// ---------------------------------------------------------------------------

static jsi::Function make_timer_fn(runner* r, bool repeat) {
    return jsi::Function::createFromHostFunction(
        *r->rt,
        jsi::PropNameID::forAscii(*r->rt, repeat ? "setInterval" : "setTimeout"),
        2,
        [r, repeat](jsi::Runtime& rt, const jsi::Value&,
                    const jsi::Value* args, size_t count) -> jsi::Value {
            if (count < 1 || !args[0].isObject()) return jsi::Value(0.0);
            int64_t delay = (count >= 2 && args[1].isNumber())
                ? static_cast<int64_t>(args[1].getNumber()) : 0;
            if (delay < 0) delay = 0;
            timer_entry entry(
                r->next_timer_id++,
                std::chrono::steady_clock::now() + std::chrono::milliseconds(delay),
                repeat, delay,
                jsi::Value(rt, args[0])   // deep-copy through the runtime
            );
            int64_t id = entry.id;
            r->timers.push_back(std::move(entry));
            return jsi::Value(static_cast<double>(id));
        });
}

static jsi::Function make_clear_timer_fn(runner* r) {
    return jsi::Function::createFromHostFunction(
        *r->rt,
        jsi::PropNameID::forAscii(*r->rt, "clearTimeout"),
        1,
        [r](jsi::Runtime&, const jsi::Value&,
            const jsi::Value* args, size_t count) -> jsi::Value {
            if (count >= 1 && args[0].isNumber()) {
                int64_t id = static_cast<int64_t>(args[0].getNumber());
                auto& tv = r->timers;
                tv.erase(std::remove_if(tv.begin(), tv.end(),
                    [id](const timer_entry& e) { return e.id == id; }),
                    tv.end());
            }
            return jsi::Value::undefined();
        });
}

static jsi::Function make_raf_fn(runner* r) {
    return jsi::Function::createFromHostFunction(
        *r->rt,
        jsi::PropNameID::forAscii(*r->rt, "requestAnimationFrame"),
        1,
        [r](jsi::Runtime& rt, const jsi::Value&,
            const jsi::Value* args, size_t count) -> jsi::Value {
            if (count < 1 || !args[0].isObject()) return jsi::Value(0.0);
            timer_entry entry(
                r->next_timer_id++,
                std::chrono::steady_clock::now() + std::chrono::milliseconds(16),
                false, 0,
                jsi::Value(rt, args[0]));
            int64_t id = entry.id;
            r->timers.push_back(std::move(entry));
            return jsi::Value(static_cast<double>(id));
        });
}

static jsi::Function make_queue_microtask_fn(runner* r) {
    return jsi::Function::createFromHostFunction(
        *r->rt,
        jsi::PropNameID::forAscii(*r->rt, "queueMicrotask"),
        1,
        [r](jsi::Runtime& rt, const jsi::Value&,
            const jsi::Value* args, size_t count) -> jsi::Value {
            if (count < 1 || !args[0].isObject()) return jsi::Value::undefined();
            // Schedule at time-zero: pump loop fires it before sleeping.
            timer_entry entry(
                r->next_timer_id++,
                std::chrono::steady_clock::now(),
                false, 0,
                jsi::Value(rt, args[0]));
            r->timers.push_back(std::move(entry));
            return jsi::Value::undefined();
        });
}

// ---------------------------------------------------------------------------
// fetch (synchronous libcurl → resolved/rejected Promise)
// ---------------------------------------------------------------------------

static jsi::Function make_fetch_fn(runner* r) {
    return jsi::Function::createFromHostFunction(
        *r->rt,
        jsi::PropNameID::forAscii(*r->rt, "fetch"),
        1,
        [](jsi::Runtime& rt, const jsi::Value&,
           const jsi::Value* args, size_t count) -> jsi::Value {
            if (count < 1) throw jsi::JSError(rt, "fetch: url required");

            std::string url = args[0].getString(rt).utf8(rt);
            http::request_options opts;

            if (count >= 2 && args[1].isObject()) {
                auto options = args[1].getObject(rt);
                auto method_v = options.getProperty(rt, "method");
                if (method_v.isString()) opts.method = method_v.getString(rt).utf8(rt);
                auto body_v = options.getProperty(rt, "body");
                if (body_v.isString()) opts.body = body_v.getString(rt).utf8(rt);
                // headers: we skip parsing — BotGuard runner doesn't set custom request headers
            }

            auto http_result = http::request(url, opts);

            if (auto* err = std::get_if<http::http_error>(&http_result)) {
                const std::string msg = "fetch failed: " + err->message;
                // Return Promise.reject(new Error(msg))
                auto script = "Promise.reject(new Error(" +
                    ([&]() -> std::string {
                        // JSON-escape the message
                        std::string out = "\"";
                        for (char c : msg) {
                            if (c == '"')  out += "\\\"";
                            else if (c == '\\') out += "\\\\";
                            else if (c == '\n') out += "\\n";
                            else out += c;
                        }
                        out += "\"";
                        return out;
                    }()) + "))";
                return rt.evaluateJavaScript(
                    std::make_shared<jsi::StringBuffer>(script), "<fetch-reject>");
            }

            const auto& resp_data = std::get<http::response>(http_result);
            const std::string body = resp_data.body;
            const long status = resp_data.status;

            jsi::Object resp(rt);
            resp.setProperty(rt, "ok",     jsi::Value(status >= 200 && status < 300));
            resp.setProperty(rt, "status", jsi::Value(static_cast<double>(status)));

            // .text() → Promise.resolve(body_str)
            auto text_fn = jsi::Function::createFromHostFunction(rt,
                jsi::PropNameID::forAscii(rt, "text"), 0,
                [body](jsi::Runtime& rt2, const jsi::Value&,
                       const jsi::Value*, size_t) -> jsi::Value {
                    auto Promise = rt2.global().getPropertyAsObject(rt2, "Promise");
                    auto resolve = Promise.getPropertyAsFunction(rt2, "resolve");
                    return resolve.callWithThis(rt2, Promise,
                        jsi::String::createFromUtf8(rt2, body));
                });
            resp.setProperty(rt, "text", jsi::Value(rt, std::move(text_fn)));

            // .json() → Promise.resolve(JSON.parse(body))
            auto json_fn = jsi::Function::createFromHostFunction(rt,
                jsi::PropNameID::forAscii(rt, "json"), 0,
                [body](jsi::Runtime& rt2, const jsi::Value&,
                       const jsi::Value*, size_t) -> jsi::Value {
                    auto JSON = rt2.global().getPropertyAsObject(rt2, "JSON");
                    auto parse = JSON.getPropertyAsFunction(rt2, "parse");
                    auto parsed = parse.callWithThis(rt2, JSON,
                        jsi::String::createFromUtf8(rt2, body));
                    auto Promise = rt2.global().getPropertyAsObject(rt2, "Promise");
                    auto resolve = Promise.getPropertyAsFunction(rt2, "resolve");
                    return resolve.callWithThis(rt2, Promise, std::move(parsed));
                });
            resp.setProperty(rt, "json", jsi::Value(rt, std::move(json_fn)));

            // .arrayBuffer() → Promise.resolve(Uint8Array-ish)
            auto ab_fn = jsi::Function::createFromHostFunction(rt,
                jsi::PropNameID::forAscii(rt, "arrayBuffer"), 0,
                [body](jsi::Runtime& rt2, const jsi::Value&,
                       const jsi::Value*, size_t) -> jsi::Value {
                    // Build a Uint8Array by indexing; sufficient for BG usage.
                    auto Uint8Array_ctor = rt2.global().getPropertyAsFunction(rt2, "Uint8Array");
                    auto arr = Uint8Array_ctor.callAsConstructor(rt2,
                        jsi::Value(static_cast<double>(body.size())));
                    // Fill each element
                    if (arr.isObject()) {
                        auto obj = arr.getObject(rt2);
                        for (size_t i = 0; i < body.size(); ++i) {
                            obj.setProperty(rt2,
                                jsi::PropNameID::forAscii(rt2, std::to_string(i).c_str()),
                                jsi::Value(static_cast<double>(
                                    static_cast<unsigned char>(body[i]))));
                        }
                        auto Promise = rt2.global().getPropertyAsObject(rt2, "Promise");
                        auto resolve = Promise.getPropertyAsFunction(rt2, "resolve");
                        return resolve.callWithThis(rt2, Promise, std::move(obj));
                    }
                    return jsi::Value::undefined();
                });
            resp.setProperty(rt, "arrayBuffer", jsi::Value(rt, std::move(ab_fn)));

            // Wrap in Promise.resolve(resp)
            auto Promise = rt.global().getPropertyAsObject(rt, "Promise");
            auto resolve = Promise.getPropertyAsFunction(rt, "resolve");
            return resolve.callWithThis(rt, Promise, std::move(resp));
        });
}

// ---------------------------------------------------------------------------
// crypto.getRandomValues
// ---------------------------------------------------------------------------

static jsi::Function make_get_random_values_fn(runner* r) {
    return jsi::Function::createFromHostFunction(
        *r->rt,
        jsi::PropNameID::forAscii(*r->rt, "getRandomValues"),
        1,
        [](jsi::Runtime& rt, const jsi::Value&,
           const jsi::Value* args, size_t count) -> jsi::Value {
            if (count < 1 || !args[0].isObject()) return jsi::Value::undefined();
            auto arr = args[0].getObject(rt);
            auto length_v = arr.getProperty(rt, "length");
            if (!length_v.isNumber()) return jsi::Value(rt, arr);
            size_t len = static_cast<size_t>(length_v.getNumber());

            std::random_device rd;
            std::mt19937 rng(rd());
            std::uniform_int_distribution<int> dist(0, 255);
            for (size_t i = 0; i < len; ++i) {
                arr.setProperty(rt,
                    jsi::PropNameID::forAscii(rt, std::to_string(i).c_str()),
                    jsi::Value(static_cast<double>(dist(rng))));
            }
            return jsi::Value(rt, std::move(arr));
        });
}

// ---------------------------------------------------------------------------
// Browser environment setup
// ---------------------------------------------------------------------------

static void setup_browser_env(runner* r) {
    using namespace constants;
    jsi::Runtime& rt = *r->rt;

    // -- timers ---------------------------------------------------------------
    rt.global().setProperty(rt, "setTimeout",
        jsi::Value(rt, make_timer_fn(r, false)));
    rt.global().setProperty(rt, "setInterval",
        jsi::Value(rt, make_timer_fn(r, true)));
    rt.global().setProperty(rt, "setImmediate",       // node compat
        jsi::Value(rt, make_timer_fn(r, false)));
    rt.global().setProperty(rt, "clearTimeout",
        jsi::Value(rt, make_clear_timer_fn(r)));
    rt.global().setProperty(rt, "clearInterval",
        jsi::Value(rt, make_clear_timer_fn(r)));
    rt.global().setProperty(rt, "clearImmediate",
        jsi::Value(rt, make_clear_timer_fn(r)));
    rt.global().setProperty(rt, "requestAnimationFrame",
        jsi::Value(rt, make_raf_fn(r)));
    rt.global().setProperty(rt, "cancelAnimationFrame",
        jsi::Value(rt, make_clear_timer_fn(r)));
    rt.global().setProperty(rt, "queueMicrotask",
        jsi::Value(rt, make_queue_microtask_fn(r)));

    // -- fetch ----------------------------------------------------------------
    rt.global().setProperty(rt, "fetch",
        jsi::Value(rt, make_fetch_fn(r)));

    // -- console (via JS — simpler than individual HostFunctions) ------------
    eval_js(r, R"JS(
(function() {
    function _log() {
        var parts = [];
        for (var i = 0; i < arguments.length; i++) {
            try { parts.push(String(arguments[i])); } catch(e) { parts.push('[object]'); }
        }
    }
    globalThis.console = {
        log:   _log, error: _log, warn:  _log,
        info:  _log, debug: _log, trace: _log,
        group: _log, groupEnd: _log, groupCollapsed: _log,
        time:  function() {}, timeEnd: function() {}, timeLog: function() {},
        count: function() {}, countReset: function() {}, clear: function() {},
        assert: function(cond) { if (!cond) _log.apply(null, ['Assertion failed:'].concat(Array.prototype.slice.call(arguments,1))); },
        dir: _log, dirxml: _log, table: _log
    };
})();
)JS", "<console>");

    // -- performance.now ------------------------------------------------------
    eval_js(r, R"JS(
(function() {
    var _start = Date.now();
    globalThis.performance = {
        now: function() { return Date.now() - _start; },
        timing: (function(){var t=Date.now(); return {navigationStart:t,fetchStart:t,domainLookupStart:t,domainLookupEnd:t,connectStart:t,connectEnd:t,secureConnectionStart:0,requestStart:t,responseStart:t,responseEnd:t,domLoading:t,domInteractive:t,domContentLoadedEventStart:t,domContentLoadedEventEnd:t,domComplete:t,loadEventStart:t,loadEventEnd:t,unloadEventStart:0,unloadEventEnd:0,redirectStart:0,redirectEnd:0};}()),
        navigation: { type: 0, redirectCount: 0 },
        timeOrigin: Date.now(),
        getEntries: function() { return []; },
        getEntriesByType: function() { return []; },
        getEntriesByName: function() { return []; },
        mark: function() {}, measure: function() {},
        clearMarks: function() {}, clearMeasures: function() {},
        clearResourceTimings: function() {}
    };
})();
)JS", "<performance>");

    // -- crypto ---------------------------------------------------------------
    rt.global().setProperty(rt, "crypto",
        [&]() {
            jsi::Object cryp(rt);
            cryp.setProperty(rt, "getRandomValues",
                jsi::Value(rt, make_get_random_values_fn(r)));
            auto rand_uuid = jsi::Function::createFromHostFunction(rt,
                jsi::PropNameID::forAscii(rt, "randomUUID"), 0,
                [](jsi::Runtime& rt2, const jsi::Value&,
                   const jsi::Value*, size_t) -> jsi::Value {
                    static std::random_device rd;
                    static std::mt19937 rng(rd());
                    static std::uniform_int_distribution<int> d(0, 15);
                    static const char* hex = "0123456789abcdef";
                    std::string uuid(36, '-');
                    for (int i = 0; i < 36; ++i) {
                        if (i==8||i==13||i==18||i==23) continue;
                        uuid[i] = hex[d(rng)];
                    }
                    uuid[14] = '4';
                    uuid[19] = "89ab"[d(rng) % 4];
                    return jsi::Value(rt2,
                        jsi::String::createFromUtf8(rt2, uuid));
                });
            cryp.setProperty(rt, "randomUUID",
                jsi::Value(rt, std::move(rand_uuid)));
            return jsi::Value(rt, std::move(cryp));
        }());

    // -- navigator (via JS) ---------------------------------------------------
    eval_js(r,
        std::string("(function() { var nav = {"
            "userAgent: '") + USER_AGENT + "',"
            "language: 'en-US', languages: ['en-US','en'], platform: 'MacIntel',"
            "vendor: 'Google Inc.', appName: 'Netscape', appCodeName: 'Mozilla',"
            "product: 'Gecko', onLine: true, cookieEnabled: true, doNotTrack: null,"
            "hardwareConcurrency: " + std::to_string(HARDWARE_CONCURRENCY) + ","
            "maxTouchPoints: 0, webdriver: false,"
            "plugins: [], mimeTypes: [],"
            "deviceMemory: 8, pdfViewerEnabled: true,"
            "permissions: { query: function(){ return Promise.resolve({state:'granted'}); } },"
            "sendBeacon: function(){ return true; },"
            "mediaDevices: { enumerateDevices: function(){ return Promise.resolve([]); },"
                "getUserMedia: function(){ return Promise.reject(new Error('No media')); },"
                "getDisplayMedia: function(){ return Promise.reject(new Error('No media')); } },"
            "connection: { effectiveType:'4g', rtt:50, downlink:10, saveData:false, type:'wifi',"
                "addEventListener:function(){}, removeEventListener:function(){} },"
            "serviceWorker: { ready: Promise.resolve({active:null,installing:null,waiting:null,"
                "update:function(){},unregister:function(){}}), controller:null,"
                "register:function(){ return Promise.reject(new Error('No SW')); },"
                "getRegistration:function(){ return Promise.resolve(undefined); },"
                "getRegistrations:function(){ return Promise.resolve([]); },"
                "addEventListener:function(){}, removeEventListener:function(){} },"
            "storage: { estimate:function(){ return Promise.resolve({usage:0,quota:0}); },"
                "persist:function(){ return Promise.resolve(false); },"
                "persisted:function(){ return Promise.resolve(false); } }"
        "};"
        "try { Object.defineProperty(globalThis,'navigator',{value:nav,configurable:false,writable:false,enumerable:true}); }"
        "catch(e) { globalThis.navigator = nav; }"
        "})();",
        "<navigator>");

    // -- screen ---------------------------------------------------------------
    eval_js(r,
        std::string("(function(){"
            "globalThis.screen={"
                "width:") + std::to_string(SCREEN_WIDTH) + ","
                "height:" + std::to_string(SCREEN_HEIGHT) + ","
                "availWidth:" + std::to_string(SCREEN_WIDTH) + ","
                "availHeight:" + std::to_string(SCREEN_HEIGHT - 25) + ","
                "colorDepth:24,pixelDepth:24,"
                "orientation:{type:'landscape-primary',angle:0}"
            "};"
        "})();",
        "<screen>");

    // -- location, origin, document, window, self, global --------------------
    eval_js(r, R"JS(
(function() {
    globalThis.location = {
        href: 'https://www.youtube.com/', origin: 'https://www.youtube.com',
        protocol: 'https:', host: 'www.youtube.com', hostname: 'www.youtube.com',
        port: '', pathname: '/', search: '', hash: '',
        assign: function(){}, replace: function(){}, reload: function(){}
    };
    globalThis.origin = 'https://www.youtube.com';

    function makeEl(tag) {
        var el = {
            tagName: tag, id: '', className: '', innerHTML: '', textContent: '',
            style: {}, children: [],
            getAttribute: function(){ return null; },
            setAttribute: function(){}, removeAttribute: function(){},
            hasAttribute: function(){ return false; },
            appendChild: function(c){ return c; }, removeChild: function(c){ return c; },
            addEventListener: function(){}, removeEventListener: function(){},
            dispatchEvent: function(){ return true; },
            getBoundingClientRect: function(){ return {top:0,left:0,bottom:0,right:0,width:0,height:0,x:0,y:0}; }
        };
        if (tag === 'CANVAS') {
            el.getContext = function(){ return null; };
            el.toDataURL = function(){ return 'data:,'; };
            el.width = 300; el.height = 150;
        }
        return el;
    }

    globalThis.document = {
        createElement: function(tag){ return makeEl(String(tag).toUpperCase()); },
        getElementById: function(){ return null; },
        querySelector: function(){ return null; },
        querySelectorAll: function(){ return []; },
        getElementsByTagName: function(){ return []; },
        getElementsByClassName: function(){ return []; },
        createTextNode: function(t){ return {nodeType:3,textContent:t}; },
        addEventListener: function(){}, removeEventListener: function(){},
        dispatchEvent: function(){ return true; },
        cookie: '', referrer: 'https://www.youtube.com/', domain: 'www.youtube.com',
        title: 'YouTube', readyState: 'complete',
        URL: 'https://www.youtube.com/', documentURI: 'https://www.youtube.com/',
        characterSet: 'UTF-8', charset: 'UTF-8', nodeType: 9,
        body: makeEl('BODY'), head: makeEl('HEAD'), documentElement: makeEl('HTML'),
        location: globalThis.location
    };

    globalThis.window       = globalThis;
    globalThis.self         = globalThis;
    globalThis.global       = globalThis;

    globalThis.getComputedStyle  = function(){ return {}; };
    globalThis.matchMedia        = function(q){ return {matches:false,media:q,onchange:null,
        addListener:function(){},removeListener:function(){},
        addEventListener:function(){},removeEventListener:function(){}}; };
    globalThis.addEventListener    = function(){};
    globalThis.removeEventListener = function(){};
    globalThis.dispatchEvent       = function(){ return true; };
})();
)JS", "<dom-env>");

    // -- atob / btoa (verbatim from v8_runner.cpp) ----------------------------
    eval_js(r, R"JS(
(function() {
    var chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/';
    globalThis.btoa = function(s) {
        var i, b = '', l = s.length;
        for (i = 0; i < l; i += 3) {
            var c0 = s.charCodeAt(i), c1 = i+1<l ? s.charCodeAt(i+1) : 0, c2 = i+2<l ? s.charCodeAt(i+2) : 0;
            b += chars[c0>>2] + chars[((c0&3)<<4)|(c1>>4)] + (i+1<l ? chars[((c1&15)<<2)|(c2>>6)] : '=') + (i+2<l ? chars[c2&63] : '=');
        }
        return b;
    };
    globalThis.atob = function(s) {
        s = s.replace(/[^A-Za-z0-9+/]/g, '');
        var i, n = s.length, b = '';
        for (i = 0; i < n; i += 4) {
            var a = chars.indexOf(s[i]), c = chars.indexOf(s[i+1]), d = chars.indexOf(s[i+2]), e = chars.indexOf(s[i+3]);
            b += String.fromCharCode((a<<2)|(c>>4));
            if (d !== -1) b += String.fromCharCode(((c&15)<<4)|(d>>2));
            if (e !== -1) b += String.fromCharCode(((d&3)<<6)|e);
        }
        return b;
    };
})();
)JS", "<atob-btoa>");

    // -- TextEncoder / TextDecoder (verbatim from v8_runner.cpp) -------------
    eval_js(r, R"JS(
(function() {
    globalThis.TextEncoder = function TextEncoder() {};
    TextEncoder.prototype.encoding = 'utf-8';
    TextEncoder.prototype.encode = function(s) {
        var out = [], i = 0, n = s.length;
        while (i < n) {
            var c = s.charCodeAt(i++);
            if (c < 0x80) { out.push(c); }
            else if (c < 0x800) { out.push(0xC0|(c>>6), 0x80|(c&63)); }
            else if (c >= 0xD800 && c < 0xDC00 && i < n) {
                var c2 = s.charCodeAt(i);
                if (c2 >= 0xDC00 && c2 < 0xE000) {
                    var cp = 0x10000 + ((c & 0x3FF) << 10) + (c2 & 0x3FF);
                    out.push(0xF0|(cp>>18), 0x80|((cp>>12)&63), 0x80|((cp>>6)&63), 0x80|(cp&63));
                    i++;
                } else { out.push(0xEF, 0xBF, 0xBD); }
            } else if (c >= 0xD800 && c < 0xE000) { out.push(0xEF,0xBF,0xBD); }
            else { out.push(0xE0|(c>>12), 0x80|((c>>6)&63), 0x80|(c&63)); }
        }
        return new Uint8Array(out);
    };
    globalThis.TextDecoder = function TextDecoder(enc) { this.encoding = enc || 'utf-8'; };
    TextDecoder.prototype.decode = function(buf) {
        if (!buf) return '';
        var bytes = buf instanceof Uint8Array ? buf : new Uint8Array(buf);
        var s = '', i = 0;
        while (i < bytes.length) {
            var b = bytes[i++];
            if (b < 0x80) { s += String.fromCharCode(b); }
            else if (b < 0xE0) { s += String.fromCharCode(((b&31)<<6)|(bytes[i++]&63)); }
            else if (b < 0xF0) {
                var b2=bytes[i++],b3=bytes[i++];
                s += String.fromCharCode(((b&15)<<12)|((b2&63)<<6)|(b3&63));
            } else {
                var b2=bytes[i++],b3=bytes[i++],b4=bytes[i++];
                var cp = ((b&7)<<18)|((b2&63)<<12)|((b3&63)<<6)|(b4&63);
                cp -= 0x10000;
                s += String.fromCharCode(0xD800+(cp>>10), 0xDC00+(cp&0x3FF));
            }
        }
        return s;
    };
})();
)JS", "<text-encoder-decoder>");

    // -- URL (verbatim from v8_runner.cpp) ------------------------------------
    eval_js(r, R"JS(
(function() {
    globalThis.URL = function URL(url, base) {
        if (typeof url !== 'string') throw new TypeError('URL is not a string');
        this.href = url;
        var m = url.match(/^([a-z][a-z0-9+\-.]*:)\/\/([^/?#]*)([^?#]*)(\?[^#]*)?(#.*)?$/i);
        if (m) {
            this.protocol = m[1]; this.host = m[2]; this.pathname = m[3]||'/';
            this.search = m[4]||''; this.hash = m[5]||''; this.origin = m[1]+'//'+m[2];
        } else { this.href = url; this.protocol=''; this.host=''; this.pathname=url; this.search=''; this.hash=''; this.origin=''; }
        this.username=''; this.password=''; this.port='';
        var hm = this.host.match(/^([^:]+):(\d+)$/);
        if (hm) { this.hostname = hm[1]; this.port = hm[2]; } else { this.hostname = this.host; }
    };
    URL.prototype.toString = function() { return this.href; };
    URL.createObjectURL = function() { return ''; };
    URL.revokeObjectURL = function() {};
    URL.parse = function(url, base) { try { return new URL(url, base); } catch (e) { return null; } };
    URL.canParse = function(url, base) { try { new URL(url, base); return true; } catch (e) { return false; } };
})();
)JS", "<URL>");

    // -- Event stubs (verbatim from v8_runner.cpp) ----------------------------
    eval_js(r, R"JS(
(function() {
    globalThis.Event = function Event(type, opts) { this.type = type; this.bubbles = !!(opts&&opts.bubbles); this.cancelable = !!(opts&&opts.cancelable); };
    globalThis.CustomEvent = function CustomEvent(type, opts) { this.type = type; this.detail = opts&&opts.detail; };
    globalThis.MessageEvent = function MessageEvent(type, opts) { this.type = type; this.data = opts&&opts.data; };
})();
)JS", "<Event>");

    // -- HTML element stubs (verbatim from v8_runner.cpp) --------------------
    eval_js(r, R"JS(
(function() {
    globalThis.HTMLCanvasElement = function HTMLCanvasElement() {};
    HTMLCanvasElement.prototype.getContext = function() { return null; };
    HTMLCanvasElement.prototype.toDataURL  = function() { return 'data:,'; };
    globalThis.HTMLElement = function HTMLElement() {};
    globalThis.HTMLInputElement = function HTMLInputElement() {};
    globalThis.HTMLVideoElement = function HTMLVideoElement() {};
    globalThis.HTMLImageElement = function HTMLImageElement() {};
    globalThis.Image = function Image(w,h) { this.width=w||0; this.height=h||0; };
})();
)JS", "<HTMLElement>");

    // -- WebGL stubs (verbatim from v8_runner.cpp) ----------------------------
    eval_js(r, R"JS(
(function() {
    globalThis.WebGLRenderingContext  = function WebGLRenderingContext()  {};
    globalThis.WebGL2RenderingContext = function WebGL2RenderingContext() {};
})();
)JS", "<WebGL>");

    // -- Browser extras (verbatim from v8_runner.cpp) -------------------------
    eval_js(r, R"JS(
(function() {
    if (!globalThis.chrome) {
        globalThis.chrome = {
            runtime: {},
            app: { isInstalled: false },
            csi: function() { return {}; },
            loadTimes: function() { return { firstPaintTime: 0 }; }
        };
    }
    function makeStorage() {
        var data = {};
        return {
            get length() { return Object.keys(data).length; },
            key: function(i) { return Object.keys(data)[i] || null; },
            getItem: function(k) { return Object.prototype.hasOwnProperty.call(data, k) ? data[k] : null; },
            setItem: function(k, v) { data[k] = String(v); },
            removeItem: function(k) { delete data[k]; },
            clear: function() { data = {}; }
        };
    }
    if (!globalThis.localStorage)   globalThis.localStorage   = makeStorage();
    if (!globalThis.sessionStorage) globalThis.sessionStorage = makeStorage();
    if (!globalThis.Storage)        globalThis.Storage        = function Storage() {};

    if (!globalThis.indexedDB) {
        globalThis.indexedDB = {
            open: function() {
                var req = { onsuccess: null, onerror: null, onupgradeneeded: null, result: null, error: null };
                setTimeout(function() {
                    if (typeof req.onerror === 'function')
                        req.onerror({ type: 'error', target: req });
                }, 0);
                return req;
            },
            deleteDatabase: function() { return { onsuccess: null, onerror: null }; },
            databases: function() { return Promise.resolve([]); }
        };
        globalThis.IDBDatabase    = function IDBDatabase() {};
        globalThis.IDBTransaction = function IDBTransaction() {};
        globalThis.IDBRequest     = function IDBRequest() {};
        globalThis.IDBFactory     = function IDBFactory() {};
        globalThis.IDBObjectStore = function IDBObjectStore() {};
        globalThis.IDBIndex       = function IDBIndex() {};
        globalThis.IDBKeyRange    = function IDBKeyRange() {};
        globalThis.IDBCursor      = function IDBCursor() {};
    }

    if (!globalThis.Worker)           globalThis.Worker           = function Worker() { throw new Error('Worker not supported'); };
    if (!globalThis.SharedWorker)     globalThis.SharedWorker     = function SharedWorker() { throw new Error('SharedWorker not supported'); };
    if (!globalThis.BroadcastChannel) globalThis.BroadcastChannel = function BroadcastChannel() { this.postMessage=function(){}; this.close=function(){}; this.addEventListener=function(){}; this.removeEventListener=function(){}; };
    if (!globalThis.MessageChannel)   globalThis.MessageChannel   = function MessageChannel() { this.port1={}; this.port2={}; };
    if (!globalThis.MessagePort)      globalThis.MessagePort      = function MessagePort() {};

    var noopObserver = function() { this.observe=function(){}; this.unobserve=function(){}; this.disconnect=function(){}; this.takeRecords=function(){return[];}; };
    if (!globalThis.MutationObserver)     globalThis.MutationObserver     = noopObserver;
    if (!globalThis.IntersectionObserver) globalThis.IntersectionObserver = noopObserver;
    if (!globalThis.ResizeObserver)       globalThis.ResizeObserver       = noopObserver;
    if (!globalThis.PerformanceObserver)  globalThis.PerformanceObserver  = noopObserver;
    if (!globalThis.ReportingObserver)    globalThis.ReportingObserver    = noopObserver;

    if (!globalThis.Notification) {
        globalThis.Notification = function Notification() {};
        globalThis.Notification.permission = 'default';
        globalThis.Notification.requestPermission = function() { return Promise.resolve('default'); };
    }

    if (!globalThis.Headers) {
        globalThis.Headers = function Headers(init) {
            var map = {};
            if (init && typeof init === 'object') {
                for (var k in init) map[String(k).toLowerCase()] = String(init[k]);
            }
            this.append = function(k,v) { map[String(k).toLowerCase()] = String(v); };
            this.delete = function(k) { delete map[String(k).toLowerCase()]; };
            this.get = function(k) { var v=map[String(k).toLowerCase()]; return v===undefined?null:v; };
            this.has = function(k) { return Object.prototype.hasOwnProperty.call(map,String(k).toLowerCase()); };
            this.set = function(k,v) { map[String(k).toLowerCase()] = String(v); };
            this.forEach = function(cb) { for (var k in map) cb(map[k],k,this); };
        };
    }
    if (!globalThis.Request)  globalThis.Request  = function Request()  {};
    if (!globalThis.Response) globalThis.Response = function Response() {};
    if (!globalThis.Blob)     globalThis.Blob     = function Blob() { this.size=0; this.type=''; };
    if (!globalThis.File)     globalThis.File     = function File()     {};
    if (!globalThis.FormData) globalThis.FormData = function FormData() { this.append=function(){}; this.delete=function(){}; this.get=function(){return null;}; this.has=function(){return false;}; this.set=function(){}; };
    if (!globalThis.AbortController) {
        globalThis.AbortController = function AbortController() {
            var self = this;
            this.signal = { aborted:false, addEventListener:function(){}, removeEventListener:function(){}, dispatchEvent:function(){return true;} };
            this.abort = function() { self.signal.aborted=true; };
        };
    }
    if (!globalThis.AbortSignal) globalThis.AbortSignal = function AbortSignal() {};

    if (!globalThis.EventTarget) {
        globalThis.EventTarget = function EventTarget() {};
        globalThis.EventTarget.prototype.addEventListener    = function() {};
        globalThis.EventTarget.prototype.removeEventListener = function() {};
        globalThis.EventTarget.prototype.dispatchEvent       = function() { return true; };
    }

    if (globalThis.crypto && !globalThis.crypto.subtle) {
        function rejector(name) {
            return function() { return Promise.reject(new Error('subtle.' + name + ' not supported')); };
        }
        try {
            Object.defineProperty(globalThis.crypto, 'subtle', {
                value: {
                    encrypt:rejector('encrypt'),    decrypt:rejector('decrypt'),
                    sign:rejector('sign'),          verify:rejector('verify'),
                    digest:rejector('digest'),      generateKey:rejector('generateKey'),
                    deriveKey:rejector('deriveKey'),deriveBits:rejector('deriveBits'),
                    importKey:rejector('importKey'),exportKey:rejector('exportKey'),
                    wrapKey:rejector('wrapKey'),    unwrapKey:rejector('unwrapKey')
                }
            });
        } catch (e) {}
    }
    if (!globalThis.SubtleCrypto) globalThis.SubtleCrypto = function SubtleCrypto() {};
    if (!globalThis.CryptoKey)    globalThis.CryptoKey    = function CryptoKey()    {};

    if (!globalThis.history) {
        globalThis.history = {
            length:1, scrollRestoration:'auto', state:null,
            back:function(){}, forward:function(){}, go:function(){},
            pushState:function(){}, replaceState:function(){}
        };
    }
    if (typeof globalThis.devicePixelRatio !== 'number') globalThis.devicePixelRatio = 1;
    if (typeof globalThis.innerWidth  !== 'number') globalThis.innerWidth  = 1280;
    if (typeof globalThis.innerHeight !== 'number') globalThis.innerHeight = 720;
    if (typeof globalThis.outerWidth  !== 'number') globalThis.outerWidth  = 1280;
    if (typeof globalThis.outerHeight !== 'number') globalThis.outerHeight = 720;
    if (typeof globalThis.scrollX     !== 'number') globalThis.scrollX     = 0;
    if (typeof globalThis.scrollY     !== 'number') globalThis.scrollY     = 0;

    if (!globalThis.requestIdleCallback)  globalThis.requestIdleCallback  = function(cb) { return setTimeout(function(){ cb({didTimeout:false,timeRemaining:function(){return 0;}}); },1); };
    if (!globalThis.cancelIdleCallback)   globalThis.cancelIdleCallback   = function(id) { clearTimeout(id); };

    if (globalThis.performance) {
        if (!globalThis.performance.getEntries)        globalThis.performance.getEntries        = function() { return []; };
        if (!globalThis.performance.getEntriesByType)  globalThis.performance.getEntriesByType  = function() { return []; };
        if (!globalThis.performance.getEntriesByName)  globalThis.performance.getEntriesByName  = function() { return []; };
        if (!globalThis.performance.mark)              globalThis.performance.mark              = function() {};
        if (!globalThis.performance.measure)           globalThis.performance.measure           = function() {};
        if (!globalThis.performance.clearMarks)        globalThis.performance.clearMarks        = function() {};
        if (!globalThis.performance.clearMeasures)     globalThis.performance.clearMeasures     = function() {};
        if (!globalThis.performance.clearResourceTimings) globalThis.performance.clearResourceTimings = function() {};
    }

    if (!globalThis.Intl) globalThis.Intl = {};

    if (globalThis.navigator) {
        if (!globalThis.navigator.mediaDevices) {
            globalThis.navigator.mediaDevices = {
                enumerateDevices: function() { return Promise.resolve([]); },
                getUserMedia:     function() { return Promise.reject(new Error('No media')); },
                getDisplayMedia:  function() { return Promise.reject(new Error('No media')); }
            };
        }
        if (!globalThis.navigator.connection) {
            globalThis.navigator.connection = { effectiveType:'4g', rtt:50, downlink:10, saveData:false, type:'wifi', addEventListener:function(){}, removeEventListener:function(){} };
        }
    }
    if (!globalThis.AudioContext)        globalThis.AudioContext        = function AudioContext()        {};
    if (!globalThis.OfflineAudioContext) globalThis.OfflineAudioContext = function OfflineAudioContext() {};
    if (!globalThis.RTCPeerConnection)   globalThis.RTCPeerConnection   = function RTCPeerConnection()   {};
    if (!globalThis.RTCSessionDescription) globalThis.RTCSessionDescription = function RTCSessionDescription() {};
    if (!globalThis.RTCIceCandidate)     globalThis.RTCIceCandidate     = function RTCIceCandidate()     {};

    if (!globalThis.CSSStyleSheet)       globalThis.CSSStyleSheet       = function CSSStyleSheet() { this.cssRules=[]; };
    if (!globalThis.CSSStyleDeclaration) globalThis.CSSStyleDeclaration = function CSSStyleDeclaration() {};
    if (!globalThis.CSS) {
        globalThis.CSS = {
            supports: function() { return false; },
            escape:   function(s) { return String(s); }
        };
    }
    if (!globalThis.FontFace) globalThis.FontFace = function FontFace() {};

    if (!globalThis.Document)      globalThis.Document      = function Document()      {};
    if (!globalThis.HTMLDocument)  globalThis.HTMLDocument  = function HTMLDocument()  {};
    if (!globalThis.Window)        globalThis.Window        = function Window()        {};
    if (!globalThis.Navigator)     globalThis.Navigator     = function Navigator()     {};
    if (!globalThis.Screen)        globalThis.Screen        = function Screen()        {};
    if (!globalThis.Location)      globalThis.Location      = function Location()      {};
    if (!globalThis.PluginArray)   globalThis.PluginArray   = function PluginArray()   {};
    if (!globalThis.MimeTypeArray) globalThis.MimeTypeArray = function MimeTypeArray() {};
    if (!globalThis.Plugin)        globalThis.Plugin        = function Plugin()        {};
    if (!globalThis.MimeType)      globalThis.MimeType      = function MimeType()      {};
    if (!globalThis.DOMException)  globalThis.DOMException  = function DOMException(msg, name) { this.message=msg||''; this.name=name||'Error'; };
    if (!globalThis.DOMParser)     globalThis.DOMParser     = function DOMParser()     {};
    if (!globalThis.XMLSerializer) globalThis.XMLSerializer = function XMLSerializer() {};
    if (!globalThis.XMLHttpRequest)globalThis.XMLHttpRequest= function XMLHttpRequest(){};
    if (!globalThis.XPathEvaluator)globalThis.XPathEvaluator= function XPathEvaluator(){};
    if (!globalThis.SVGElement)    globalThis.SVGElement    = function SVGElement()    {};
    if (!globalThis.SVGSVGElement) globalThis.SVGSVGElement = function SVGSVGElement() {};
})();
)JS", "<browser-extras>");
}

// ---------------------------------------------------------------------------
// Event loop pump
// ---------------------------------------------------------------------------

static bool pump_event_loop(runner* r,
                             std::function<bool()> condition,
                             int64_t timeout_ms = 15000) {
    const auto deadline = std::chrono::steady_clock::now() +
                          std::chrono::milliseconds(timeout_ms);

    while (!condition()) {
        if (std::chrono::steady_clock::now() > deadline) return false;

        const auto now = std::chrono::steady_clock::now();

        // Snapshot ready timer IDs
        std::vector<int64_t> ready_ids;
        for (const auto& t : r->timers) {
            if (t.fire_at <= now) ready_ids.push_back(t.id);
        }

        for (int64_t id : ready_ids) {
            auto it = std::find_if(r->timers.begin(), r->timers.end(),
                [id](const timer_entry& e) { return e.id == id; });
            if (it == r->timers.end()) continue;

            // Deep-copy the callback through the runtime so we can safely
            // mutate r->timers (erase / update) before calling it.
            jsi::Value cb(*r->rt, it->callback);
            const bool repeat      = it->repeat;
            const int64_t interval = it->interval_ms;

            if (!repeat) {
                r->timers.erase(it);
            } else {
                it->fire_at = now + std::chrono::milliseconds(interval);
            }

            if (cb.isObject()) {
                auto obj = cb.getObject(*r->rt);
                if (obj.isFunction(*r->rt)) {
                    try {
                        obj.asFunction(*r->rt).call(*r->rt);
                    } catch (...) {}
                }
            }
        }

        // Drain microtasks (resolves Promises scheduled during timer callbacks)
        r->rt->drainMicrotasks();

        if (!condition()) {
            std::this_thread::sleep_for(std::chrono::milliseconds(1));
        }
    }
    return true;
}

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

std::variant<runner*, run_error> create_runner(
        const std::string& interpreter_js,
        const std::string& program,
        const std::string& global_name) {

    auto* r = new runner;
    r->rt   = facebook::hermes::makeHermesRuntime();

    try {
        setup_browser_env(r);

        // Evaluate the full BotGuard bundle (bgutils-js + jsdom-minimal + entry).
        // After eval, globalThis exposes runBotguard / newMinter / mint.
        eval_js(r, BG_FULL_BUNDLE_JS, "<bg-full-bundle>");

        // Stash interpreter/program/globalName for the driver scripts.
        r->rt->global().setProperty(*r->rt, "__epo_interp_src__",
            jsi::String::createFromUtf8(*r->rt, interpreter_js));
        r->rt->global().setProperty(*r->rt, "__epo_program__",
            jsi::String::createFromUtf8(*r->rt, program));
        r->rt->global().setProperty(*r->rt, "__epo_global_name__",
            jsi::String::createFromUtf8(*r->rt, global_name));
        r->rt->global().setProperty(*r->rt, "__epo_user_agent__",
            jsi::String::createFromUtf8(*r->rt, constants::USER_AGENT));

    } catch (const jsi::JSError& e) {
        destroy_runner(r);
        return run_error{e.getMessage()};
    } catch (const std::exception& e) {
        destroy_runner(r);
        return run_error{e.what()};
    }

    return r;
}

snapshot_outcome run_snapshot(runner* r) {
    // Same driver script as v8_runner.cpp — pure JS, engine-agnostic.
    static const char* driver = R"JS(
(function() {
    globalThis.__epo_state__ = null;
    globalThis.runBotguard(
        globalThis.__epo_interp_src__,
        globalThis.__epo_program__,
        globalThis.__epo_global_name__,
        globalThis.__epo_user_agent__
    ).then(function(snapshot) {
        globalThis.__epo_state__ = { snapshot: snapshot, done: true, error: null };
    }).catch(function(e) {
        globalThis.__epo_state__ = {
            done: true,
            error: e && e.message ? e.message : String(e)
        };
    });
})();
)JS";

    try {
        eval_js(r, driver, "<snapshot-driver>");
    } catch (const jsi::JSError& e) {
        return run_error{e.getMessage()};
    }

    r->rt->drainMicrotasks();

    bool ok = pump_event_loop(r, [&]() {
        auto state = get_nested(r, "__epo_state__");
        if (state.isNull() || state.isUndefined()) return false;
        return js_bool(r, "__epo_state__.done");
    });

    if (!ok) return run_error{"Timed out waiting for BotGuard snapshot"};

    const std::string err = js_string(r, "__epo_state__.error");
    if (!err.empty() && err != "null") return run_error{"BotGuard snapshot error: " + err};

    const std::string snapshot = js_string(r, "__epo_state__.snapshot");
    if (snapshot.empty()) return run_error{"BotGuard snapshot returned empty string"};

    return snapshot_result{snapshot};
}

po_token_outcome run_mint(runner* r,
                          const std::string& integrity_token,
                          const std::string& content_binding) {
    r->rt->global().setProperty(*r->rt, "__epo_integrity_token__",
        jsi::String::createFromUtf8(*r->rt, integrity_token));
    r->rt->global().setProperty(*r->rt, "__epo_content_binding__",
        jsi::String::createFromUtf8(*r->rt, content_binding));

    // Same driver script as v8_runner.cpp.
    static const char* driver = R"JS(
(function() {
    globalThis.__epo_mint_state__ = null;
    globalThis.newMinter(globalThis.__epo_integrity_token__)
        .then(function() { return globalThis.mint(globalThis.__epo_content_binding__); })
        .then(function(po_token) {
            globalThis.__epo_mint_state__ = { po_token: po_token, done: true, error: null };
        })
        .catch(function(e) {
            globalThis.__epo_mint_state__ = {
                done: true,
                error: e && e.message ? e.message : String(e)
            };
        });
})();
)JS";

    try {
        eval_js(r, driver, "<mint-driver>");
    } catch (const jsi::JSError& e) {
        return run_error{e.getMessage()};
    }

    r->rt->drainMicrotasks();

    bool ok = pump_event_loop(r, [&]() {
        auto state = get_nested(r, "__epo_mint_state__");
        if (state.isNull() || state.isUndefined()) return false;
        return js_bool(r, "__epo_mint_state__.done");
    });

    if (!ok) return run_error{"Timed out waiting for PoToken minting"};

    const std::string err = js_string(r, "__epo_mint_state__.error");
    if (!err.empty() && err != "null") return run_error{"PoToken minting error: " + err};

    const std::string token = js_string(r, "__epo_mint_state__.po_token");
    if (token.empty()) return run_error{"Minted PoToken is empty"};

    return po_token_result{token};
}

void destroy_runner(runner* r) {
    if (!r) return;
    // Timers must be cleared before the runtime is destroyed; their jsi::Value
    // callbacks would be invalidated by rt.reset() otherwise.
    r->timers.clear();
    r->rt.reset();
    delete r;
}

} // namespace epotoken::hermes_runner
