#include "nsig_runner.h"

// NSIG_DECIPHER_JS — generated by CMake from src/nsig_decipher.min.js
#include "nsig_bundle.h"

#include <hermes/hermes.h>
#include <jsi/jsi.h>

#include <hermes/Public/GCConfig.h>
#include <hermes/Public/RuntimeConfig.h>

#include <exception>
#include <memory>
#include <string>

namespace jsi = facebook::jsi;

namespace epotoken::nsig_runner {

struct runner {
    std::unique_ptr<facebook::hermes::HermesRuntime> rt;
};

namespace {

jsi::Value call_global(jsi::Runtime& rt, const char* name, const std::string& arg) {
    auto fn = rt.global().getPropertyAsFunction(rt, name);
    return fn.call(rt, jsi::String::createFromUtf8(rt, arg));
}

} // namespace

std::variant<runner*, run_error> create_runner() {
    auto* r = new runner;
    // The decipher runtime only evaluates the ~180 KB extracted script and
    // transforms a string, so a small GC heap keeps its footprint down (the
    // default 32 MB initial heap dominated peak RSS otherwise).
    auto config = ::hermes::vm::RuntimeConfig::Builder()
        .withGCConfig(::hermes::vm::GCConfig::Builder()
            .withInitHeapSize(1u << 20)     // 1 MB
            .withMaxHeapSize(96u << 20)     // 96 MB ceiling
            .build())
        .build();
    r->rt = facebook::hermes::makeHermesRuntime(config);
    try {
        r->rt->evaluateJavaScript(
            std::make_shared<jsi::StringBuffer>(std::string(NSIG_DECIPHER_JS)),
            "<nsig-decipher>");
    } catch (const jsi::JSError& e) {
        destroy_runner(r);
        return run_error{e.getMessage()};
    } catch (const std::exception& e) {
        destroy_runner(r);
        return run_error{e.what()};
    }
    return r;
}

std::variant<std::monostate, run_error> setup(runner* r, const std::string& output) {
    jsi::Runtime& rt = *r->rt;
    try {
        auto res = call_global(rt, "__epo_setupNsig", output);
        if (!(res.isBool() && res.getBool()))
            return run_error{"nsig setup returned false"};
        return std::monostate{};
    } catch (const jsi::JSError& e) {
        return run_error{e.getMessage()};
    } catch (const std::exception& e) {
        return run_error{std::string("nsig setup: ") + e.what()};
    }
}

decipher_outcome decipher(runner* r, const std::string& n) {
    jsi::Runtime& rt = *r->rt;
    try {
        auto res = call_global(rt, "__epo_decipherN", n);
        if (!res.isString())
            return run_error{"nsig decipher returned non-string"};
        return res.getString(rt).utf8(rt);
    } catch (const jsi::JSError& e) {
        return run_error{e.getMessage()};
    } catch (const std::exception& e) {
        return run_error{std::string("nsig decipher: ") + e.what()};
    }
}

void destroy_runner(runner* r) {
    delete r;
}

} // namespace epotoken::nsig_runner
