/**
 * EPoToken — WASM (browser / Deno) binding.
 *
 * The WASM module exports only pure-compute primitives (visitor_data, body
 * builders, parsers, placeholder token) because WASM has no raw sockets and
 * no embedded V8. This wrapper drives the network side with fetch() and runs
 * BotGuard via bgutils-js (which works natively in browsers, where it can
 * rely on the host DOM instead of jsdom).
 *
 * Usage:
 *   import createModule from './epotoken.js';
 *   import { createEPoToken } from './index.js';
 *
 *   const wasm = await createModule();
 *   const ep   = createEPoToken(wasm);
 *
 *   const { poToken, placeholderPoToken, visitorData, identifier }
 *     = await ep.generatePoToken();
 */

import { BotGuardClient, WebPoMinter } from 'bgutils-js';
import type { IBgConfig } from 'bgutils-js';

// ---------------------------------------------------------------------------
// WASM module surface (generated by Emscripten EMSCRIPTEN_BINDINGS)
// ---------------------------------------------------------------------------

interface WasmChallengeResult {
    success: boolean;
    interpreterUrl: string;
    interpreterJs:  string;
    program:        string;
    globalName:     string;
    error:          string;
}

interface WasmTokenResult {
    success: boolean;
    token:   string;
    error:   string;
}

export interface WasmContextOverrides {
    visitorData?:      string;
    clientVersion?:    string;
    hl?:               string;
    gl?:               string;
    userAgent?:        string;
    osName?:           string;
    osVersion?:        string;
    browserName?:      string;
    browserVersion?:   string;
    timeZone?:         string;
    utcOffsetMinutes?: number;
}

export interface WasmConstants {
    userAgent:              string;
    requestKey:             string;
    googApiKey:             string;
    googBaseUrl:            string;
    createEndpoint:         string;
    generateItEndpoint:     string;
    innertubeApiKey:        string;
    innertubeBaseUrl:       string;
    innertubeClientName:    string;
    innertubeClientNameId:  string;
    innertubeClientVersion: string;
    ytBaseUrl:              string;
    staticVisitorId:        string;
}

export interface EPoTokenWasmModule {
    parseChallengeResponse(body: string):     WasmChallengeResult;
    parseAttResponse(body: string):           WasmChallengeResult;
    parseGenerateItResponse(body: string):    WasmTokenResult;
    generatePlaceholderToken(id: string, clientState: number): WasmTokenResult;
    generateVisitorData():                    string;
    generateRandomVisitorData():              string;
    encodeVisitorData(id: string, ts: number): string;
    decodeVisitorDataId(visitorData: string): string;
    buildAttGetBody(opts: WasmContextOverrides): string;
    buildGenerateItBody(snapshot: string):    string;
    buildChallengeCreateBody():               string;
    descramble(encoded: string):              string;
    getConstants():                           WasmConstants;
}

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export interface PoTokenResult {
    poToken:            string;
    placeholderPoToken: string;
    visitorData:        string;
    identifier:         string;
}

export interface GeneratePoTokenOptions {
    /** Defaults to the session's visitor_data. */
    contentBinding?: string;
    /**
     * Overrides the interpreter URL returned by /att/get. Useful when the
     * interpreter JS is served from a cache, mirror, or pinned commit.
     */
    interpreterUrl?: string;
    /** Pre-fetched interpreter JS (skips the network fetch entirely). */
    interpreterJs?:  string;
    /** Context overrides for the /att/get body (locale, UA, etc.). */
    context?:        WasmContextOverrides;
    /** Custom fetch implementation (defaults to globalThis.fetch). */
    fetch?:          typeof fetch;
}

// ---------------------------------------------------------------------------
// Wrapper
// ---------------------------------------------------------------------------

function unwrap<T extends { success: boolean; error: string }>(
        r: T, ctx: string): T {
    if (!r.success) throw new Error(`${ctx}: ${r.error}`);
    return r;
}

export interface EPoTokenApi {
    /** Drives the entire PoToken flow using fetch() + bgutils-js. */
    generatePoToken(opts?: GeneratePoTokenOptions): Promise<PoTokenResult>;

    /** Cold-start placeholder token (synchronous; pure C++). */
    generatePlaceholderToken(identifier: string, clientState?: number): string;

    /** Fresh visitor_data with a random 11-char id. */
    generateVisitorData(): string;

    /** Lower-level access to the WASM exports. */
    wasm: EPoTokenWasmModule;
}

export function createEPoToken(wasm: EPoTokenWasmModule): EPoTokenApi {
    const constants = wasm.getConstants();

    async function generatePoToken(
            opts: GeneratePoTokenOptions = {}): Promise<PoTokenResult> {
        const doFetch = opts.fetch ?? globalThis.fetch.bind(globalThis);

        // 1. Build /att/get body. Use a fresh random visitor unless caller supplied one.
        const ctx: WasmContextOverrides = { ...(opts.context ?? {}) };
        if (!ctx.visitorData) ctx.visitorData = wasm.generateRandomVisitorData();
        const visitorData = ctx.visitorData;

        const attBody = wasm.buildAttGetBody(ctx);

        // 2. POST /att/get
        const attUrl =
            `${constants.innertubeBaseUrl}/att/get?prettyPrint=false&alt=json`;
        const attResp = await doFetch(attUrl, {
            method:  'POST',
            headers: {
                'content-type':              'application/json',
                'accept':                    '*/*',
                'x-youtube-client-name':     constants.innertubeClientNameId,
                'x-youtube-client-version':  ctx.clientVersion ?? constants.innertubeClientVersion,
                'x-goog-visitor-id':         visitorData,
                'user-agent':                ctx.userAgent ?? constants.userAgent,
                'origin':                    constants.ytBaseUrl,
                'referer':                   `${constants.ytBaseUrl}/`,
            },
            body: attBody,
        });
        if (!attResp.ok) {
            throw new Error(`/att/get returned HTTP ${attResp.status}`);
        }
        const challenge = unwrap(
            wasm.parseAttResponse(await attResp.text()),
            '/att/get parse');

        // 3. Get interpreter JS.
        let interpreterJs: string;
        if (opts.interpreterJs) {
            interpreterJs = opts.interpreterJs;
        } else {
            const url = opts.interpreterUrl || challenge.interpreterUrl;
            if (!url && challenge.interpreterJs) {
                interpreterJs = challenge.interpreterJs;
            } else {
                if (!url) throw new Error('No interpreter URL or embedded JS available');
                const r = await doFetch(url, {
                    headers: {
                        'user-agent': ctx.userAgent ?? constants.userAgent,
                        'referer':    `${constants.ytBaseUrl}/`,
                    },
                });
                if (!r.ok) {
                    throw new Error(
                        `Failed to fetch interpreter JS: HTTP ${r.status}`);
                }
                interpreterJs = await r.text();
            }
        }
        if (!interpreterJs) throw new Error('Interpreter JS is empty');

        // 4. Run BotGuard via bgutils-js (browser DOM provides jsdom-equivalent).
        const webPoSignalOutput: unknown[] = [];
        const bgConfig: IBgConfig = {
            program:    challenge.program,
            globalName: challenge.globalName,
            globalObj:  globalThis,
        };
        const botGuard = await BotGuardClient.create(bgConfig, interpreterJs);
        const snapshot = await botGuard.snapshot({ webPoSignalOutput });

        // 5. POST GenerateIT.
        const genBody = wasm.buildGenerateItBody(snapshot);
        const genResp = await doFetch(constants.generateItEndpoint, {
            method:  'POST',
            headers: {
                'content-type':    'application/json+protobuf',
                'x-goog-api-key':  constants.googApiKey,
                'x-user-agent':    'grpc-web-javascript/0.1',
                'user-agent':      ctx.userAgent ?? constants.userAgent,
            },
            body: genBody,
        });
        if (!genResp.ok) {
            throw new Error(`GenerateIT returned HTTP ${genResp.status}`);
        }
        const integrityToken = unwrap(
            wasm.parseGenerateItResponse(await genResp.text()),
            'GenerateIT parse').token;

        // 6. Mint PoToken.
        const binding = opts.contentBinding ?? visitorData;
        const minter = await WebPoMinter.create(integrityToken, webPoSignalOutput);
        const poToken = await minter.mintAsWebsafeString(binding);

        // 7. Placeholder token (pure C++).
        const placeholderPoToken = unwrap(
            wasm.generatePlaceholderToken(binding, 1),
            'placeholder').token;

        return { poToken, placeholderPoToken, visitorData, identifier: binding };
    }

    return {
        generatePoToken,
        generatePlaceholderToken: (id, cs = 1) =>
            unwrap(wasm.generatePlaceholderToken(id, cs), 'placeholder').token,
        generateVisitorData: () => wasm.generateRandomVisitorData(),
        wasm,
    };
}
